#ifndef TASK_PRIORITIES_H
#define TASK_PRIORITIES_H

#define TERMINAL_TASK_PRIORITY        tskIDLE_PRIORITY + 1
#define GPIO_BLINK_TASK_PRIORITY      tskIDLE_PRIORITY + 2
#define GPIO_SUBCOMMAND_TASK_PRIORITY tskIDLE_PRIORITY + 3
#define CLI_TASK_PRIORITY             tskIDLE_PRIORITY + 4

#endif
