#ifndef TASK_PRIORITIES_H
#define TASK_PRIORITIES_H

#define GPIO_BLINK_TASK_PRIORITY tskIDLE_PRIORITY + 1
#define TERMINAL_TASK_PRIORITY   tskIDLE_PRIORITY + 2
#define CLI_TASK_PRIORITY        tskIDLE_PRIORITY + 3

#endif
