#ifndef TASK_PRIORITIES_H
#define TASK_PRIORITIES_H

#define GPIO_BLINK_TASK_PRIORITY tskIDLE_PRIORITY + 1
#define I2C_TASK_PRIORITY        tskIDLE_PRIORITY + 2
#define TERMINAL_TASK_PRIORITY   tskIDLE_PRIORITY + 3
#define CLI_TASK_PRIORITY        tskIDLE_PRIORITY + 4

#endif
